# Generated by Django 5.1.1 on 2024-10-23 11:18

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponsesCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=200, verbose_name='votre commentaire')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
            managers=[
                ('managed_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu du commentaire')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.billet')),
            ],
            managers=[
                ('managed_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
