# Generated by Django 5.1.1 on 2024-10-23 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=' ', help_text='Entrez votre nom et votre(vos) prénom(s)', max_length=250, null=True, verbose_name='Nom et prénoms du demandeur')),
                ('mail', models.EmailField(default=' ', help_text='Entrez votre email courant', max_length=254, verbose_name='Email du demandeur')),
                ('numero', models.CharField(default=' ', help_text='Entrez votre(vos) numéros de téléphone', max_length=250, null=True, verbose_name='Numéros du demandeur')),
                ('domaine', models.CharField(default=' ', help_text="Précisez le nom du domaine que vous désirez <span class='fw-bolder'>exemple: www.yume.ci</span> <br> ou donnez juste le nom de l'application <span class='fw-bolder'>exemple: YumeStore </span>.", max_length=100, null=True, verbose_name="Nom de domaine de l'organisation")),
                ('type', models.CharField(choices=[('Annuaire', 'Annuaire en ligne'), ('Ecommerce', 'Application Ecommerce'), ('Vitrine', 'Site Vitrine'), ('Blog', 'Blog'), ('Forum', 'Forum'), ('Formation', 'Formation en ligne'), ('CTR', 'Communication en temps réel')], default='Vitrine', help_text="Quel type d'application désirez vous Choisissez parmi les éléments proposez", max_length=250, null=True, verbose_name="Type d'application")),
                ('produits', models.TextField(default=' ', help_text='Indiquez les produits et/ou les services vendus (marques, gammes et lignes de produits...)', null=True, verbose_name='Produits et/ou services')),
                ('objectifs', models.TextField(default='', help_text='Détaillez le ou les objectifs attendus avec cette nouvelle application. Vous pouvez découper vous objectifs en 2 parties : quantitatifs et qualitatifs.', null=True, verbose_name='Objectifs attendus')),
                ('objectifs_pdf', models.FileField(blank=True, help_text='Si vos objectifs sont au format pdf alors laissez téléversé le document pdf contenant vos objectifs bien détaillés', null=True, upload_to='formulaire/visualid', validators=[django.core.validators.FileExtensionValidator('pdf', message='Le fichier doit être au format pdf')], verbose_name='Objectifs au format pdf')),
                ('clientele', models.TextField(default='', help_text='Décrivez le profil des clients que vous espérez obtenir pour votre entreprise ? Décrivez au maximum vos cibles, leurs âges, leurs habitudes...', null=True, verbose_name='Profil de la clientèle')),
                ('clientele_pdf', models.FileField(default='', help_text='Décrivez le profil des clients que vous espérez obtenir pour votre entreprise ? Décrivez au maximum vos cibles, leurs âges, leurs habitudes...', null=True, upload_to='', verbose_name='Profil de la clientèle au format pdf')),
                ('description', models.TextField(default='', help_text='Donnez nous une description du site que vous aimeriez avoir en précisant (couleur, design et autres)', null=True, verbose_name="Description de l'application")),
                ('description_pdf', models.FileField(default='', help_text='Donnez nous une description du site que vous aimeriez avoir en précisant (couleur, design et autres)', null=True, upload_to='', verbose_name='Description détaillée du site web')),
                ('date_butoire', models.DateField(help_text='Avez-vous une date butoire pour le lancement du projet ?', null=True, verbose_name='Date de lancement')),
                ('wireframe_file', models.FileField(help_text='Avez-vous une structure définie du site e-commerce au format pdf ou image (jpg,png,et jpeg)?', null=True, upload_to='', verbose_name='Structure du site Web au format image ou pdf')),
                ('visualid', models.FileField(blank=True, help_text='Si vous avez une identité visuelle téléverser le document au format pdf sinon laissez le champ vide', null=True, upload_to='formulaire/visualid/%Y', validators=[django.core.validators.FileExtensionValidator('pdf', message='Le fichier doit être au format pdf')], verbose_name='Identité visuelle')),
                ('reference', models.CharField(default='', help_text='Avez vous des sites de référence ( des sites que vous appréciez)? énumerez les', max_length=250, null=True, verbose_name='Application de référence')),
                ('logo', models.FileField(blank=True, help_text='Téléversez votre logo si vous en avez un', null=True, upload_to='formulaires/logo/%Y', validators=[django.core.validators.FileExtensionValidator(['jpg', 'svg', 'png', 'jpeg'], message='Le fichier doit être au format svg,png,jpeg ou jpg')], verbose_name='Logo de votre organisation')),
                ('couleurs', models.TextField(default='Mes couleurs sont: ', help_text='Définissez vos couleurs et vos préférences graphiques', null=True, verbose_name='Couleur(s)')),
                ('texteseo', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default=True, help_text='Voulez-vous que nous revoyons vos textes pour les adapter aux référencement web (ou voulez vous que nous rédigeons votre contenu textuel)? ', max_length=10, verbose_name='Référencement SEO')),
                ('entretien', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default=True, help_text="Voulez vous que nous nous chargeons de l'entretien du site après sa création ? ", max_length=10, verbose_name='Entretien')),
                ('promotion', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default=True, help_text='Voulez-vous que nous fassions la promotion de votre futur site web?', max_length=10, verbose_name='Promotion')),
                ('keywords', models.TextField(default='', help_text='Précisez les mots clés que vous désirez.', null=True, verbose_name='Mots clés')),
                ('divers', models.TextField(default='', help_text='Dites ce que vous désirez de plus pour votre site que nous avons peut-être omis .', null=True, verbose_name='Ajouts')),
                ('slug', models.SlugField(default=' ', verbose_name="Slug de l'utilisateur")),
            ],
        ),
        migrations.CreateModel(
            name='Annuaire',
            fields=[
                ('generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formulaire.generic')),
            ],
            bases=('formulaire.generic',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formulaire.generic')),
                ('commentaire', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default=True, help_text='Voulez-vous un suivi des commentaires du blog?', max_length=250, verbose_name='Voulez-vous que votre blog possède un suivi des commentaires?')),
            ],
            bases=('formulaire.generic',),
        ),
        migrations.CreateModel(
            name='CTR',
            fields=[
                ('generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formulaire.generic')),
            ],
            bases=('formulaire.generic',),
        ),
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formulaire.generic')),
                ('fiche', models.TextField(default='', help_text='Définissez ce que comportera chaque fiche produit (comment sera présenté un produit)?', null=True, verbose_name=' Fiche produit')),
                ('paiement', models.TextField(default='', help_text='Quelles sont les solutions de paiement à intégrer sur le site?(paypal, mtn money, moov money, orange money...)', null=True, verbose_name='Moyens de paiement')),
                ('appdedie', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default=True, help_text="Voulez-vous une application mobile dédié(ou une application web) pour votre application d'ecommerce?", max_length=250, verbose_name="Voulez-vous une application mobile dédié(ou une application web) pour votre application d'ecommerce?")),
            ],
            bases=('formulaire.generic',),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formulaire.generic')),
            ],
            bases=('formulaire.generic',),
        ),
        migrations.CreateModel(
            name='Vitrine',
            fields=[
                ('generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formulaire.generic')),
            ],
            bases=('formulaire.generic',),
        ),
    ]
