# Generated by Django 5.1.1 on 2024-10-23 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='titre du billet')),
                ('icon', models.CharField(default='newspaper', max_length=100, verbose_name='Icône du billet')),
                ('slug', models.SlugField(max_length=250, verbose_name='slug du blog')),
                ('introduction', models.TextField(verbose_name='Introduction du billet')),
                ('image_introduction', models.ImageField(blank=True, null=True, upload_to='blog/%Y', verbose_name="Image de l'introduction")),
                ('conclusion', models.TextField(verbose_name='Conclusion du blog')),
                ('image_conclusion', models.ImageField(blank=True, null=True, upload_to='blog/%Y', verbose_name="Image de l'conclusion")),
                ('date_de_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('publier', models.BooleanField(default=False, verbose_name='Publier ?')),
                ('auteur', models.CharField(default='Yume', max_length=250, verbose_name='Auteur du billet')),
            ],
            options={
                'verbose_name': 'Billet de Blog',
                'verbose_name_plural': 'Billets de blog',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=250, verbose_name='pseudo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='blog/avatars', verbose_name='avatar')),
                ('contenu', models.TextField(verbose_name='contenu du commentaire')),
                ('visiteur', models.CharField(max_length=250, verbose_name='adresse ip du visiteur')),
                ('billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.billet')),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='Titre de la partie')),
                ('contenu', models.TextField(verbose_name='Contenu de la parite')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog/%Y', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog/%Y', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog/%Y', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='blog/%Y', verbose_name='Image 4')),
                ('publier', models.BooleanField(default=False, verbose_name='Publier ?')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug pour les liens')),
                ('billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.billet')),
            ],
        ),
        migrations.CreateModel(
            name='ReponsesCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=200, verbose_name='votre pseudo')),
                ('contenu', models.TextField(max_length=200, verbose_name='votre commentaire')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.commentaire')),
            ],
        ),
    ]
