# Generated by Django 5.1.1 on 2024-10-23 11:18

import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('numero', models.CharField(default='Aucun numéro enregistré', max_length=100, verbose_name='numéro de téléphone')),
                ('adresse', models.CharField(default='Aucune adresse enregistrée', max_length=250, verbose_name="adresse de l'utilisateur ")),
                ('is_referenced', models.BooleanField(default=False, verbose_name="l'utilisateur est-il referencé ?")),
                ('slug', models.SlugField(max_length=250, verbose_name='champ automatique généré pour le référecement')),
                ('stars', models.IntegerField(default=0, verbose_name="Nombre d'étoiles pour le positionnement")),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse email')),
                ('is_active', models.BooleanField(default=True, verbose_name="L'utilisateur est-il actif?")),
                ('is_admin', models.BooleanField(default=False, verbose_name="L'utilisateur est-il administrateur du site?")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Liste des Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('icone', models.CharField(default='bag-fill', max_length=200, verbose_name="Icône de l'activité ")),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu du témoignage')),
                ('auteur', models.CharField(max_length=200, verbose_name='Auteur du témoignage')),
                ('date_of_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière date de publication')),
                ('details', models.TextField(verbose_name='Détails du témoignage')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='temoignage', verbose_name='logo du groupe')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
            },
        ),
        migrations.CreateModel(
            name='TypeFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='type du formulaire')),
                ('is_available', models.BooleanField(verbose_name='Le formulaire est-il disponible')),
                ('icon', models.CharField(default='award', max_length=250, verbose_name='Icône du formulaire ')),
                ('description', models.TextField(verbose_name='Description du formulaire')),
                ('lien', models.CharField(default='ecommerce', max_length=50, verbose_name='Lien Formulaire')),
            ],
            options={
                'verbose_name': 'Type de formulaire',
                'verbose_name_plural': 'Type de formulaires',
            },
        ),
        migrations.CreateModel(
            name='Utilitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_barre_de_recherche', models.CharField(default='faites une recherche sur Yume', max_length=250, verbose_name="titre de la barre de recherche page d'accueil")),
                ('slogan', models.CharField(default='donnez vous le droit de rêvez', max_length=250, verbose_name='slogan')),
                ('slogan_reduit', models.CharField(default='Rêvez', max_length=250, verbose_name='slogan réduit pour petit écran')),
                ('home_image', models.ImageField(upload_to='utilitaire', verbose_name="Image de la page d'Accueil")),
                ('last_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la dernière modification')),
            ],
            options={
                'verbose_name': 'Utilitaire',
                'verbose_name_plural': 'Liste des Utilitaires',
            },
            managers=[
                ('managed_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='titre de la valeur')),
                ('texte', models.TextField(verbose_name='Valeur')),
                ('icon', models.CharField(default='award', max_length=250, verbose_name='Icône de la valeur ')),
                ('image', models.ImageField(default=' ', upload_to='valeurs', verbose_name='Image de la valeur')),
            ],
            options={
                'verbose_name': 'Valeur',
                'verbose_name_plural': 'Valeurs',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.TextField(default="Acune description n'a encore été ajoutée", verbose_name='Description détaillée')),
                ('siteweb', models.CharField(default='https://www.yume.ci', max_length=250, verbose_name='url du site web')),
                ('nom_du_profil', models.CharField(default='Aucun nom de profil enregistré', max_length=250, verbose_name='nom du profil')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/%Y', verbose_name='Photo de profile')),
                ('activite', models.ManyToManyField(to='general.activite')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
            bases=('general.utilisateur',),
        ),
    ]
