# Generated by Django 5.1.1 on 2024-10-23 11:18

import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(default='Acune description enregistrée', verbose_name='description')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='date de mise en ligne')),
            ],
            options={
                'verbose_name': "Présentation de l'entreprise",
                'verbose_name_plural': "Présentations de l'entreprise ",
                'ordering': ['-release_date'],
            },
            managers=[
                ('managed_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MotDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(default=' ', verbose_name='mot du directeur')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='date de mise en ligne')),
            ],
            options={
                'verbose_name': 'Mot du Directeur',
                'verbose_name_plural': 'Mots du Directeur ',
                'ordering': ['-release_date'],
            },
            managers=[
                ('managed_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='nom')),
                ('prenom', models.CharField(max_length=250, verbose_name='prénom(s)')),
                ('description', models.TextField(default='Acune description enregistrée', verbose_name='description')),
                ('numero', models.CharField(default='Aucun numéro enregistré', max_length=100, verbose_name='numéro de téléphone')),
                ('creation_date', models.DateField(verbose_name='date de création')),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('organisation', models.CharField(max_length=100, verbose_name='Organisation')),
                ('contenu', models.TextField(verbose_name='Contenu du témoignage')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de témoignage')),
                ('publier', models.BooleanField(default=False, verbose_name='Le témoignage doit-il être publier')),
            ],
            options={
                'verbose_name': 'Temoignage',
                'verbose_name_plural': 'Temoignages',
            },
        ),
    ]
