# Generated by Django 5.1.1 on 2024-10-23 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True, verbose_name='Nom du produit')),
                ('icon', models.CharField(default='cart', max_length=100, verbose_name='icone du produit')),
                ('subtitle', models.CharField(blank=True, default=' ', max_length=250, null=True, unique=True, verbose_name='Sous titre du produit')),
                ('badge', models.CharField(choices=[('ruby', 'Ruby'), ('diamant', 'Diamant'), ('or', 'Or'), ('argent', 'Argent'), ('bronze', 'Bronze')], max_length=250, verbose_name='Badge du produit')),
                ('date_de_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'insertion du produit")),
                ('old_price', models.CharField(default='', max_length=50, verbose_name='Prix original du produit')),
                ('price', models.CharField(default='', max_length=50, verbose_name='Prix du produit')),
            ],
            options={
                'verbose_name': "Produit de l'Agence",
                'verbose_name_plural': "Liste des Produits de l'Agence ",
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, unique=True, verbose_name='Nom du service')),
                ('description', models.TextField(default=' ', verbose_name='Description du service')),
            ],
        ),
        migrations.CreateModel(
            name='Fonctionalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Non de la fonctionnalité')),
                ('inclusion', models.BooleanField(default=True, verbose_name='Fonctionalité incluse ou non?')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nombre d'inclusion de la fonctionnalité")),
                ('icon', models.CharField(default='dpad', max_length=100, verbose_name='icone du produit')),
                ('produit', models.ManyToManyField(to='agence.produit')),
            ],
        ),
    ]
